### ISSUE TITLE
1v1 Leaderboards does not show my stats

### ISSUE THREAD

**Issue by GrotheFAF** [FAForever/website#105]
1v1 Leaderboards knows my name 'Grothe' if I type it in, but shows nothing (no result line)
other names I tried, like CrusMissle don't show result neither

(If I 'next' through the list to my 'Centurion', I'm listed and stats are shown after click on 'View')
It (kinda) worked when I last used it, must be 1-3 week ago.

I deleted the site cookies (something with forum....), now it's working again.

**Comment by GrotheFAF** [comment]
User 'Grothe' and others in search are working, but 'Captainchlorgas' - even though the name shows up in 'dropdown list' - shows no result.

**Comment by Brutus5000** [comment]
I suspect the same reason as https://github.com/FAForever/website/issues/165 . As your user is showing now and the other referenced user is probably inactive on ladder I close this as duplicate of #165
