### ISSUE TITLE
Please confirm versions

### ISSUE THREAD

**Issue by og01** [FAForever/website#11]
I've forked this repo to take a look at it, I'm creating a Vagrantfile to create a reusable development environment.

I trying installing node 5.10.0 and npm install failed, can you confirm which version of node you are developing against?

Additionally it would be good to know which version of mongodb as well.

**Comment by og01** [comment]
Apologies, 5.10.0 works fine, it was a couple of issue with my environment.

Would still like to know which version of node and mongo you are using though.

**Comment by Sheeo** [comment]
Hey @og01, thanks for peeking at this repo!

There's a draft of a dockerfile here (I didn't get around to finishing it: https://github.com/FAForever/website/commit/b915f0769c69725b9f831f8ddf44ce6cdb3e052b).

It should run using latest node version, but please beware that the plan is to get rid of the mongo dependency, so don't build too much stuff relying on that.
