### ISSUE TITLE
Make password reset not require a username

### ISSUE THREAD

**Issue by Sheeo** [FAForever/website#112]
Supplying an email should suffice, the service shouldn't leak whether the account exists or not, however.

Perhaps to be cross-tracked at FAForever/api / FAForever/faf-java-api

**Comment by Brutus5000** [comment]
Already implemented in Java-API (https://github.com/FAForever/faf-java-api/pull/85).
The route takes either an email-address or a username.

**Comment by Brutus5000** [comment]
Solved quite a long time ago :)
