### ISSUE TITLE
Repair reCAPTCHA registration form

### ISSUE THREAD

**Issue by micheljung** [FAForever/website#120]
https://www.google.com/recaptcha/intro/android.html

**Comment by Raistlfiren** [comment]
@micheljung - Can you please send me a PM with the recaptcha credentials in Slack to work on this? There will need to be a new account created, preferably for test.faforever.com and faforever.com please for V2 of recaptcha.

**Comment by 1-alex98** [comment]
It exists but is broken

**Comment by 1-alex98** [comment]
https://developers.google.com/recaptcha/docs/verify

**Comment by Brutus5000** [comment]
Fixed by 428f0ee91719e44dd4b2d426c167d3283a8a51d0 and validation in the API
