### ISSUE TITLE
Add top5 ladder players widget

### ISSUE THREAD

**Issue by Brutus5000** [FAForever/website#121]
Simple way for querying: take the first 5 players in this api call https://api.faforever.com/leaderboards/ladder1v1

**Comment by Raistlfiren** [comment]
There isn't a good place for this on the homepage as it is now. The purpose of the homepage is to showcase FAF to potential new players, and I do feel like it does accomplish that. 

Should we include this on the "Competitive" page?

**Comment by Brutus5000** [comment]
This is the feadback I received from the "competetive scene". The leaderboard is already in the competetive tab, but that seems to be not visible enough.

**Comment by MrRowey** [comment]
This Could Be closed as thier Nowhere currly were this can be displayed and not realy that nessacary

**Comment by MrRowey** [comment]
@Brutus5000 Close this off as Leaderboard do this fine and once I'm down with refactoring the leaderboards it should be easier to see all this.
