### ISSUE TITLE
Loading news on website takes ages

### ISSUE THREAD

**Issue by 1-alex98** [FAForever/website#127]
Everything loads instantly apart from news. It takes awfully long or shows "Gateway Timout".

**Comment by 1-alex98** [comment]
![image](https://user-images.githubusercontent.com/19996713/34958078-8ed195d2-fa30-11e7-94b5-d9777a0a2fd3.png)

**Comment by Katharsas** [comment]
Yep same problem here. Haven't been able to see news page since 2 days ago. Also no loading in FAF client. Tested with latest Firefox and Chrome on Win 10, in germany.

Edit: Is fixed, it seems.
