### ISSUE TITLE
Manual acc verification

### ISSUE THREAD

**Issue by PhilipJFryFAF** [FAForever/website#131]
When registering a new acc the first line in the rules say:
`You must link your account to Steam after registering or wait for 24 hours before you can play. This may be waived if a trusted member of the community can vouch for you.`

Yet we do not manually verify new users.
This causes confusion among new players who don't use steam yet want to play without waiting 24 hours.

Removing the sentence about vouching would fix that.

**Comment by Rackover** [comment]
I created a PR 
https://github.com/FAForever/website/pull/152

**Comment by Katharsas** [comment]
Maybe the steam link rule should stay since its mandatory now?
