### ISSUE TITLE
incomplete gloabl leaderboard

### ISSUE THREAD

**Issue by PhilipJFryFAF** [FAForever/website#132]
The global leader board shows 5k users.
We have more than that so the last shown user is around 800 rating.

That means we pretty much don't show info about half of our player base.

**Comment by Brutus5000** [comment]
It's 10k now, but that still does not solve the problem 😛 
Looks like the website doesn't use pagination against the API results.

**Comment by MrRowey** [comment]
@Sheikah45 this can be closed leaderboard only show last active month
