### ISSUE TITLE
Client release versions not being updated

### ISSUE THREAD

**Issue by micheljung** [FAForever/website#134]
https://www.faforever.com/client

Both client links do not point to the latest version.

**Comment by Wesmania** [comment]
Python client download points to 0.16.1, which is latest stable. 0.17.x are development versions.

**Comment by 1-alex98** [comment]
https://github.com/FAForever/website/blob/c50a52c69f3ec43005ce417b22f7779552a73eac/scripts/getLatestClientRelease.js#L7 there is a js script that shoulw alays get the latest version

**Comment by 1-alex98** [comment]
but script if only run if link.json does not exist https://github.com/FAForever/website/blob/ea6614ce2bdf26ba9ab21c69998cf004ef0ce29b/routes/middleware.js#L40 Maybe not idk, I just dont get what happens here

**Comment by Sheeo** [comment]
It's not clear to me which version of the Java client it should point at? The getLatestClientRelease file is a bit of a mess, though, needs a rewrite indeed.

**Comment by micheljung** [comment]
The code does what it should, it just never runs. If it did, it would also update the python client to 0.17.x (discussed this with Wesmania in Slack already).

**Comment by Sheeo** [comment]
Having restarted the container, it does run at interval now again. I'm guessing the handlers stop working when an exception reaches the top-level which happens on occasion, will take a look next time it happens.

**Comment by Wesmania** [comment]
The link points to a development FA client version now, which is very much not ideal. This needs to be fixed ASAP.
