### ISSUE TITLE
Racist / Anti-semetic content on replay names in http://content.faforever.com/faf/vault/replays_simple.php

### ISSUE THREAD

**Issue by THaysSureFlap** [FAForever/website#135]
I found anti-semetic /racist replay names on this link:-

http://content.faforever.com/faf/vault/replays_simple.php

Text reads, "kill all kikes"

Should idealy censor replay names with hate speach.

**Comment by Brutus5000** [comment]
This is a case for the moderation. I am heavily against any kind of automated censoring as this always backfires and can easily be bypassed.

(Side note: this is a general problem and not directly related to the website.)

**Comment by Sheeo** [comment]
Please do report these issues directly to the moderation team, but thanks for notifying us on here as well.

**Comment by THaysSureFlap** [comment]
Hi,

Do you have a link to the moderation team?


Thanks

Tytn


Tytn Hays
Web Developer
SureFlap has changed its name, find out why here!
T: +44 (0) 1954 266 040
M: 07841398456
email: t.hays@surepetcare.com
Web: surepetcare.com
Sure Petcare,
6-7 The Irwin Centre
Scotland Rd, Dry Drayton, 
Cambridgeshire, 
CB23 8AR, United Kingdom
ES140917
