### ISSUE TITLE
Downlords client went beta

### ISSUE THREAD

**Issue by 1-alex98** [FAForever/website#138]
It says Alpha on the website.

**Comment by 1-alex98** [comment]
what is not updated is : 
![image](https://user-images.githubusercontent.com/19996713/39673256-3d4b047c-5139-11e8-91d6-1e30c3d040ce.png)

**Comment by 1-alex98** [comment]
pls reopen

**Comment by Geosearchef** [comment]
Why reopen?

48002c9
638e2f2
ea8d279

**Comment by Brutus5000** [comment]
Did you look at Axels screenshot?

https://github.com/FAForever/website/blob/develop/templates/views/client.pug#L15

**Comment by Geosearchef** [comment]
oh, now I get it, there's a 3rd one
