### ISSUE TITLE
Download Client button is hard to see

### ISSUE THREAD

**Issue by Blodir** [FAForever/website#14]
Both on the navbar and the presentation page.

Suggested:
- White button
- Red (alert) button

**Comment by Raistlfiren** [comment]
White Button:
[white]: http://imgur.com/L6kh4oe "White Button"

Red Button:
[red]: http://imgur.com/sOT0H5g "Red Button"

**Comment by Raistlfiren** [comment]
ping @Zyneak

**Comment by Zyneak** [comment]
Would you like the red button? It does look nicer.
