### ISSUE TITLE
UnitDataBase Url broken

### ISSUE THREAD

**Issue by 1-alex98** [FAForever/website#144]
![image](https://user-images.githubusercontent.com/19996713/40575982-8ccdcf8c-60ef-11e8-9fb6-49773f3218be.png)

**Comment by 1-alex98** [comment]
![image](https://user-images.githubusercontent.com/19996713/40575989-9ff99cb2-60ef-11e8-81cd-d2f630f8cb55.png)

**Comment by Brutus5000** [comment]
Don't use https and you're fine.
