### ISSUE TITLE
Mumble link doesn't work

### ISSUE THREAD

**Issue by Blodir** [FAForever/website#18]

**Comment by Raistlfiren** [comment]
This page will need to be re-created, correct? Are we planning on adding any new information?

**Comment by Blodir** [comment]
Think we should use the Wiki article http://wiki.faforever.com/index.php?title=Voicechat_(Mumble)

**Comment by Raistlfiren** [comment]
I hate re-creating things. I wonder if we can embed the page or pull that data somehow. (So one source isn't outdated and the other isn't)
