### ISSUE TITLE
Add information about limitation of user name change

### ISSUE THREAD

**Issue by Brutus5000** [FAForever/website#188]
We need to tell people how often they can change their username and for how long the old name will be reserved.

**Comment by 1-alex98** [comment]
it is not reserved at all right?

**Comment by Brutus5000** [comment]
A username is reserved and can be reclaimed within 6 months
And you can only change the username every 30 days

**Comment by 1-alex98** [comment]
ok

**Comment by 1-alex98** [comment]
![grafik](https://user-images.githubusercontent.com/19996713/75254451-ad4cbe00-57e0-11ea-831d-d1f11379cef2.png)
