### ISSUE TITLE
While registering you get a ✔️ marking while username is taken

### ISSUE THREAD

**Issue by jNullj** [FAForever/website#191]
I just registered and noticed that the site wouldnt notify me that the username is taken untill i submit my form. Because i started looking for a cool username i had to type the password for each taken username i attempted to register with.
It's even more confusing becouse there is a ✔️ mark that seems to imply the username is avilable.

edit: can be checked with: `https://api.test.faforever.com/data/player?filter[player]=login==%27USERNAME%27`
but for some reason it works for some usernames and not for mine

edit2 : becouse i tried on the testing server, it works perefectly on the main
`https://api.faforever.com/data/player?filter[player]=login==%27USERNAME%27`

i might send a pull request with a fix soon

**Comment by norraxx** [comment]
What is your username in faf?

**Comment by jNullj** [comment]
@norraxx 
you can test with any username, easy to replicate on chrome

im testing a solution but i cant find `account.min.js` anywhere

**Comment by Brutus5000** [comment]
Fixed with #223
