### ISSUE TITLE
unencrypted login

### ISSUE THREAD

**Issue by jNullj** [FAForever/website#193]
when clicking "Log In" user is sent to `https://www.faforever.com/login`
this url sends the user to log in at `http://api.faforever.com/login`
this adress uses **http** insted of https and is not encrypted
i used chrome's developers tool to test the request and the username and password are sent unencrypted to the server with a post request over http.

**Comment by 1-alex98** [comment]
that is issue of java api tho i think

**Comment by 1-alex98** [comment]
and further I can not reproduce this

**Comment by Brutus5000** [comment]
Just go the login page from the website. You end up on a non-https api. But I don't know why. I checked the configs on the server and they all point to https (website and api).

**Comment by jNullj** [comment]
i can do it both at regular and incognito surfing using chrome 64bit v76.0.3809.132
the same on firefox 62.0 (64-bit)

**Comment by jNullj** [comment]
after some testing, the procces goes as follows:
cliking login -> sending GET to `https://www.faforever.com/login`
-> response with 302 (Found redirection) with header redirecting to `https://api.faforever.com/oauth/authorize?response_type=code.....data...data....`
then GET request to the last url gets a result of 302 to redirect agian, this time the response has the location as `http://api.faforever.com/login`
which means the user is redirected to the /login page by the API (or atleast thats what im understanding from it)

**Comment by 1-alex98** [comment]
When I type in http://api.faforever.com/login I get redirected to https automatically, maybe that is done by my browser (opera)

**Comment by Brutus5000** [comment]
see here https://github.com/FAForever/faf-java-api/issues/334
