### ISSUE TITLE
Don't send "Success" on failed PW reset

### ISSUE THREAD

**Issue by PhilipJFryFAF** [FAForever/website#194]
https://forums.faforever.com/viewtopic.php?f=63&t=18049&p=177693#p177693
according to this user you may enter any mail address in the pw reset form (https://www.faforever.com/account/password/reset) and you will still get the positive response "Success! Your password is in the process of being reset, please reset your password by clicking on the link provided in an email."
We should check whether or not the mail used in the form is actually in use before returning this response to avoid confusion

**Comment by Geosearchef** [comment]
That is actually desired imo. You don't want to leak user email addresses by confirming they exist in the db (like not telling a user if the username or password is wrong)

**Comment by Sheeo** [comment]
Yes, this is a security/privacy feature, not a bug.

**Comment by TomCoursow** [comment]
@Sheeo 
So will this be changed?
For example I just found out that the account "SupremeCommander" exists in your Database...
But "UserIsNotExisting" is not existing... Same goes for email adresses...
This is a paradise for hackers...

![image](https://user-images.githubusercontent.com/17900090/85235223-a2630c80-b413-11ea-83ea-1272d0bb2374.png)
![image](https://user-images.githubusercontent.com/17900090/85235228-a98a1a80-b413-11ea-886c-6151744ccba8.png)

**Comment by 1-alex98** [comment]
No. Usernames are requestable by a public call from our api

**Comment by 1-alex98** [comment]
And yes, security wise using the email would be more secure. But this requires a change in general. Users see the names of other users, which means that just hiding this or even the public api call would probably not help. What is needed is the switch to email for logging in. This change is wanted but requires some serious changes. Atm we are working on changes that make the user authentificate in the server with a token from the api. This would leave one central place to login. Once we have that changing from username to email should be fairly easy...

**Comment by 1-alex98** [comment]
https://github.com/FAForever/downlords-faf-client/pull/1538

**Comment by 1-alex98** [comment]
@TomCoursow If you are interested in that topic I am happy to show u arround.

**Comment by Brutus5000** [comment]
Well I got complaints about user complaining the other way round (we said success w/o checking it). We can't make it right for everybody 😢

**Comment by TomCoursow** [comment]
@Brutus5000 From a users perspective I can totally understand but I am seeing it more from a general web application security (OWASP) side...
https://cheatsheetseries.owasp.org/cheatsheets/Forgot_Password_Cheat_Sheet.html

@axel1200 Yes I know users can see other users if they are logged in... But with that an attacker can only see the currently logged in users. But the reset functionality exposes "the whole" user database.
Using password statistics or data breaches from other sites, chances are good that hackers could steel accounts including the info that there is quite some chance that there is also an Steam account with that email maybe.
And sorry Web frontends are not my main profession, I am more of a Server/Backend or Game-Client guy so I think you don't need to show me arround but thank you very much for the offer :)

**Comment by Brutus5000** [comment]
Our player names are intentionally public (not just the logged in users): https://api.faforever.com/data/player
