### ISSUE TITLE
Player rating over time graph/statistics

### ISSUE THREAD

**Issue by arkitect-dev** [FAForever/website#21]
Replacement for the rating over time popup that the client used to have. Once implemented we'll need to webview/link in the players list in client

**Comment by Raistlfiren** [comment]
@arkitect-dev Do you happen to have a screenshot of what the client previously had? 

@Sheeo Can we pull this information from the API at the current time? I know that the ranked1v1 endpoint only gives the current rating. Would we need to access the games endpoint possibly? (I am trying to figure out if this is something that needs to be implemented with the API or we can already do it with the website)

**Comment by Sheeo** [comment]
You would need to extend the API with temporal support for ratings. Issue over there is required :)

**Comment by Raistlfiren** [comment]
Simple example:

![pasted image at 2016_05_16 17_18](https://cloud.githubusercontent.com/assets/234712/15293994/0e5018ea-1b50-11e6-98e6-aa8e2ee986c3.png)
