### ISSUE TITLE
Clan app behaves oddly if logged in from something else than website

### ISSUE THREAD

**Issue by Rackover** [FAForever/website#210]
If I log in via api.faforever.com/login , and then access the website, the clan app doesn't let me see my clan or see other clans. It probably has something to do with the way token and other things are stored in website memory when logging in, which in that case, doesnt happen (you log in while not being on the ws)

**Comment by Brutus5000** [comment]
How do you even keep the login after that? 🤔 I get redirected to the Swagger page afterwards.

**Comment by Rackover** [comment]
You're redirected to swagger, but you're still logged in. Try to query a protected route and you'll see it works. That's how I abuse it to get info when i can't open mordor

**Comment by Brutus5000** [comment]
Nope, I'm not logged in to the website. I am using Firefox on Windows and when I manually switch to faforever.com after I manually logged in via api.faforever.com/login I am not logged in on the website.

**Comment by Rackover** [comment]
Works with Vivaldi on Windows and Chrome on Windows
Before login https://i.imgur.com/lp3TpcR.jpg
After login https://i.imgur.com/jLMFyP5.jpg

**Comment by Brutus5000** [comment]
Your screenshots do not show that you are logged in to the faf-website which is the topic of this issue.

**Comment by Rackover** [comment]
Can't reproduce apparently. It happened on my computer though, so there must be a way to get this state of "half log in" that makes the clan app stutter

**Comment by Brutus5000** [comment]
Closed as it's not reproducible.
