### ISSUE TITLE
Report link leading to main page

### ISSUE THREAD

**Issue by Apofenas** [FAForever/website#227]
If players aren't logged in their profile on website it asks them to log in and than lead them to main page of web site instead of actual report page. Sometimes using report link again still doesn't work and drops players to main page

**Comment by Brutus5000** [comment]
I can't reproduce this.
When I open the report url https://www.faforever.com/account/report in an incognito tab, I get redirected to login and after login I end up on that page.

Please provide steps to reproduce your issue.

**Comment by MrRowey** [comment]
I was Able To reproduce this using Firefox.

- Cleared Cache for FAF.
- Use Report link inside FAF Client
- Asked for login and log in fine and then redirected to Main Website page and every subsiquent link click gose to the main page.
- Once ive manaual loaded the page once by going to the Drop down menu for were you login and clicking on Report Player dose the link in Aeolus work and redirect properly.

**Comment by Brutus5000** [comment]
Still can't reproduce :(
I used the report player button in the chat user list when right clicking a user. Subsequent links also lead me the report page. Where did you click? Maybe somewhere in the client the wrong link is used?

**Comment by MrRowey** [comment]
Here is what i was doing and i asume most other are doing. I did not even realised the Right clikc on user report button wa a thing. 

https://youtu.be/1LuG4860Dys

**Comment by MrRowey** [comment]
Seems it only the one Pinned at the top of Aeolus that is Having thiese issuses as the !report Command in Chat work like the right click.

**Comment by Brutus5000** [comment]
The IRC link doesn't work because the `www.` is missing. I don't know why, but it's most probably related to some domain validation during login.

**Comment by Brutus5000** [comment]
Giebmasse fixed the link in IRC. If this occurs elsewhere, we can reopen the ticket. I will not bother to fix the root cause.
