### ISSUE TITLE
User rudyeckert can't manage his clan "tier 2"

### ISSUE THREAD

**Issue by norraxx** [FAForever/website#250]
User `rudyeckert` can't manage his clan `tier 2`.

After clicking on manage clan he get an error.

https://media.discordapp.net/attachments/756334517458960434/756444543523749958/clan_managment.PNG

**Comment by 1-alex98** [comment]
yes same here... on every clan i click

**Comment by 1-alex98** [comment]
Works for me now... Please provide a way to reproduce

**Comment by MrRowey** [comment]
#322

**Comment by Rackover** [comment]
Is this still an issue?

**Comment by MrRowey** [comment]
Closing Issues as it seems to be fixed in Current website version
