### ISSUE TITLE
Support GOG License Checking

### ISSUE THREAD

**Issue by jessetilro** [FAForever/website#257]
As per the following thread on the FAF forum:
[https://forum.faforever.com/topic/281/i-bought-forged-alliance-but-not-on-steam-can-i-still-play-on-faf](https://forum.faforever.com/topic/281/i-bought-forged-alliance-but-not-on-steam-can-i-still-play-on-faf)

It would be nice if copies of Supreme Commander Forged Alliance purchased via GOG are also supported by FAF.
It looks like this should already be facilitated by their existing APIs.

What is the current status of the contact with GOG regarding license checking?
I would like to contribute to the implementation of the integration with GOG.

**Comment by Brutus5000** [comment]
I was in contact with GOG multiple times and - in theory - all they need to do is create an OAuth client in their authentication system for FAForever and send me the client id and the secret and then we can use their API.

But they didn't provide it. It's not like they refused. They just never did it. And at some point I was tired of asking for it again and again.

So if you want to do something: Complain to GOGs technical support that they should get back to us. If enough people complain they will probably do something about it. Right now it's obviously no priority to them.

**Comment by ghodan** [comment]
Email send to GOG support and got reply:

Apr 4, 2021, 14:42 GMT+2 
Hi GOG support,
The devs from FAForever are still waiting for a reply from GOG support.
See https://www.gog.com/forum/supreme_commander_series/forged_alliance_forever_support/page1
and https://github.com/FAForever/website/issues/257
Could you have a look plz and reply to the FAForever devs emails?

Genoan (GOG.com) 
Apr 7, 2021, 11:51 GMT+2 
Hello,

I'm the Tech Support Supervisor.
I believe that we have replied to one of the people involved in the project that the APIs documentation is not public.
Access to it is granted to only selected Partners and GOG Support is unable to help with gaining it.
We've also provided information that there is an unofficial documentation that might be helpful:
https://gogapidocs.readthedocs.io/en/latest/
Sorry for the inconvenience.
Regards
Genoan
GOG Customer Support

**Comment by 1-alex98** [comment]
Yeah, nice unofficial documentation but it requires a browser FAF has full control over(and we don't have control over your browser nor do we want to). So it could be done in the client and an embedded browser in there but we do Steam and would like to do GOG login in the browser over our website. So the unofficial docs are of no help with that. 

All GOG needs to do is make us a `selected Partners `(Permit us to read what games ppl own for users that authorize us) but I guess they don't want to (or just too busy to do that don't know)and that is not in FAF's hands. Btw we have are registered with Steam so we can redirect users to their side and let the user give FAF permissions to read what games they own(so we are what they call a selected Partner to Steam). Steam does not make it that hard, not sure why GOG is not getting that done.

**Comment by ghodan** [comment]
By the way, i remember a time that the FAF client did not ask for steam check when creating an account.
Why not remove the check? Its not the task of FAF team to act as DRM/Anti piracy on behalf of the owners of Sup com franchise?
In the past you could just make a FAF account with no steam side verification. If you go back to that then all GOG players with Sup com can use FAF.

**Comment by furyritchie** [comment]
> By the way, i remember a time that the FAF client did not ask for steam check when creating an account.
> Why not remove the check? Its not the task of FAF team to act as DRM/Anti piracy on behalf of the owners of Sup com franchise?
> In the past you could just make a FAF account with no steam side verification. If you go back to that then all GOG players with Sup com can use FAF.

At the moment we're doing a favour to Square Enix - they still get paid and we make sure of it. I think it is absolutely essential that we keep those checks in place. I would argue that it is the task of FAF to ensure we prevent piracy. If someone purchased on GOG it is simply bad luck at this time. It's often 80% off on steam - I got it for A$3.10 recently for a few mates.

**Comment by Brutus5000** [comment]
https://forum.faforever.com/topic/252/why-do-i-need-to-link-my-account-to-steam

**Comment by MrRowey** [comment]
@Brutus5000 with their beeing support on the API for GOG linking surly the tag could be changed for this now ?
