### ISSUE TITLE
Clan invitation throws error

### ISSUE THREAD

**Issue by Viba** [FAForever/website#269]
Currently clan invitation is broken, trying to invite player simply returns the following error:
`Error! The player nickname doesn't seem to existnull`
![image](https://user-images.githubusercontent.com/3510353/113884808-f767e780-97c7-11eb-956f-433799f3f882.png)

**Comment by Brutus5000** [comment]
The good news: it's reproducable on test.
The bad news: `null` is the exception. This doesn't make any sense. If there is no exception it shouldn't enter the catch block.
