### ISSUE TITLE
Uncaught TypeError when loading website without header

### ISSUE THREAD

**Issue by Gatsik** [FAForever/website#284]
setting User Agent to remove header and footer causes `Uncaught TypeError: Cannot read property 'classList' of null`.
probably because of this:
https://github.com/FAForever/website/blob/b6c833156108fd40aff8b34ff2d547d53d95773c/public/js/app/navigation.js

`document.querySelector('.navigation-wrapper')` results in `null` and then calling `headroom.init()` gives this error.

**Comment by 1-alex98** [comment]
Why would you do that in your user agent? Is that a common thing to do?

**Comment by Gatsik** [comment]
I wanted to display website leaderboards in python client without header and footer, but QtWebEngine spams log file with these errors.
I believe the Java client also uses UserAgent when displaying news page, but not sure if this error is reflected somewhere in the client log

**Comment by Sheikah45** [comment]
As a note apparently the website is hardcoded to not display the header and footer when the user agent is set to the faf client

**Comment by 1-alex98** [comment]
So I guess py client could do the same

**Comment by Gatsik** [comment]
Yes, that's exactly what I did and got this error
