### ISSUE TITLE
"VOD" page

### ISSUE THREAD

**Issue by Blodir** [FAForever/website#31]
under community > VODs

Get latest videos from gyle, brnk, and maybe some other guys from youtube api. Filter by game

**Comment by Raistlfiren** [comment]
@Blodir I wonder if we shouldn't just get gyle's, brnk, and zocks videos and merge them into one  list sorted by date created. The VOD implementation sounds good, but if someone has to maintain it then it may not work very well.

**Comment by Blodir** [comment]
Having only those 3 would be incredibly biased and static, I would think it more as an "community spotlight" maybe. Though we want to show off some of the best stuff for first timers as well

**Comment by Raistlfiren** [comment]
I think of something different when thinking of "Community Spotlight". It seems like you want to focus on individual users and get their story. I do like this idea, and I think it would be awesome to have on the website. I remember reading an interview with Zlo recently on the Facebook page. That would be awesome to include on the website.

Although, "VOD" to me would include just videos. Do you have any reference websites to go off of for both? Maybe we should have a "VOD" and "Community Spotlight" page on the website.

**Comment by Raistlfiren** [comment]
Actually, what about creating an official playlist on Youtube and a page for just "Learning Supreme Commander"?

**Comment by Blodir** [comment]
Good idea! We can simply add a playlist for the official FAF youtube account ( https://www.youtube.com/channel/UCkAWiUu4QE172kv-ZuyR42w ) and look up videos from that thru youtube api. Easy to manage content

**Comment by Raistlfiren** [comment]
@Blodir - I am thinking of having two new pages and links based upon this issue. `Learn` link that references the Tutorials Youtube playlist. https://www.youtube.com/playlist?list=PLWe0mYs3ObwL36zemynMh5G4b-3s5vol0

The second link would be a link under `Community` called `Spotlight` that would take all WP articles categorized as a category that showcases individual users.

... What are you thoughts on creating a third page called "VOD" that encompasses all videos from the FaForever Youtube page and also displays any users that want to include their own Youtube page as well below it (For example, zock, arkitekt, gyle, etc...)?

**Comment by MrRowey** [comment]
@Sheikah45 this can be closed it's apart of my draft PR

**Comment by Sheikah45** [comment]
Will close once the pr is merged

**Comment by Sheikah45** [comment]
You can reference this pr with Fixes #{issue} and it will close it automatically when merged
