### ISSUE TITLE
Contribute page "Intro to Development" link not found

### ISSUE THREAD

**Issue by fultonm** [FAForever/website#315]
On[ the Contribution page](https://faforever.com/contribution), clicking the "Intro to Development" link redirects to [https://wiki.faforever.com/index.php?title=Introduction_to_development](https://wiki.faforever.com/index.php?title=Introduction_to_development) which displays "Not Found".

**Comment by MrRowey** [comment]
this was updated but the new update broke the download button so in the process of looking to why that is and once we have found the source we will push the update

**Comment by MrRowey** [comment]
@fultonm the page your after is https://wiki.faforever.com/en/FAF-Development

**Comment by MrRowey** [comment]
Issue Will be fix with new website release
