### ISSUE TITLE
Install guide link broken

### ISSUE THREAD

**Issue by fultonm** [FAForever/website#321]
https://github.com/FAForever/downlords-faf-client/wiki/Install-on-Linux the "install guide" link redirects to Not Found.

Where is the Java client download link anyhow?

**Comment by Sheikah45** [comment]
I just updated the wiki link and the download package is a part of the releases on the github page or just the download client button on the front page of the website.

**Comment by fultonm** [comment]
The Client download button on the front page is an `.exe` file for Windows.

The install for Linux guide talks about extracting FAF but does not mention the ZIP folder. Like you said [it's here under "Releases" link](https://github.com/FAForever/downlords-faf-client/releases) on the downlord-faf-client repo. I feel its a little buried and could be added to that guide.

**Comment by MrRowey** [comment]
We don't officially support Linux hence why  the main download is a Windows exe . Could you point me to the exact poin in the guide for this so it can be altered to be more clear.
