### ISSUE TITLE
Donations

### ISSUE THREAD

**Issue by Sheeo** [FAForever/website#42]
Donations are currently not implemented in the test website. I think this is the most major blocker to getting it out there.

**Comment by Raistlfiren** [comment]
It is under the "Contributions" page. If you are wondering why it isn't on the homepage, then you can reference this slack link about my same inquiry - https://faforever.slack.com/archives/website/p1458074022000045

**Comment by Sheeo** [comment]
Ah, I see.

I think it will hurt our donations quite a bit if it's not directly visible in the front page -- or at least the "what's new" page (What players see in the starting tab of the client). Don't you agree?

**Comment by Raistlfiren** [comment]
I have to agree with this as well, but a few people didn't want it on the homepage. Maybe a link in the navigation to "Donate"?
