### ISSUE TITLE
Broken 1v1 guide links in beginner guide

### ISSUE THREAD

**Issue by JimStockman** [FAForever/website#435]
Hello,

The following links seem to be broken at the bottom of the following page:
https://wiki.faforever.com/en/Learning/Beginners-Guide-to-Forged-Alliance
- Cybran 1v1 guide
- Seraphim 1v1 guide
- Aeon 1v1 guide

Regards.

**Comment by JaviTrek** [comment]
Hello @JimStockman , This is more related to the FAF wiki, which isnt the FAF website. I'd recommend you hit up Rowey or Emperor Penguin on the official FAF Discord, they'll be able to help with this.

**Comment by MrRowey** [comment]
These should be fixed now :)

**Comment by JimStockman** [comment]
Thank you for your quick responses and action, appreciated :)

Regarding who I should contact when I spot a bug on the wiki, I simply
followed what seemed the most obvious to me when reading the bug report
guide.
Since the wiki is more or less the knowledge base that derives from your
website, I assumed they both fell under the same category since there is no
mention of a specific case reporting related to the wiki on the guide.

Have a nice day,
Jim
