### ISSUE TITLE
Update Github Actions

### ISSUE THREAD

**Issue by fcaps** [FAForever/website#446]
The docker/build-push-action@v1.1.1 we using in the[ release.yml](https://github.com/FAForever/website/blob/develop/.github/workflows/release.yml) is outdated and can be updated to the newest release, see [here](https://github.com/docker/build-push-action) for more info.

Don't think there will me massive improvements, but the the actions already complaining about it.
<img width="1254" alt="image" src="https://github.com/FAForever/website/assets/48691346/74a45d51-29ce-480e-b679-c39cc1804404">

**Comment by MrRowey** [comment]
Feel free to Update it has been complaining for ages, never had the time to look into it

**Comment by fcaps** [comment]
jup, i had some trail and error thing going on. did not notice github will add the ref from the fork here
