### ISSUE TITLE
Account registration

### ISSUE THREAD

**Issue by Sheeo** [FAForever/website#45]
Support registration of new accounts.

Whether we do this by direct database access or through the API doesn't matter too much.

**Comment by Raistlfiren** [comment]
Do we have a link currently? I am not sure what to do for this once, since there isn't anything visible on the current homepage to do this.

**Comment by Sheeo** [comment]
We need to actually implement the registration process in the website codebase. Currently, this is done here: https://github.com/FAForever/server/blob/develop/server/lobbyconnection.py#L208

Don't worry though, I'll grab this one.
