### ISSUE TITLE
Enable cache busting for assets on deploy

### ISSUE THREAD

**Issue by fcaps** [FAForever/website#496]
What happened:
a route got removed from production "js/app/members/newshub.json"
this route was called from a js file that got cached in the reverse-proxy.

to overcome this issue, assets should be loaded with a version qyery-parameter like "https://faforever.com/js/app/newshub.js?v=2"

**Comment by fcaps** [comment]
after investigating a bit, it seams like grunt is not supported when it comes to cache busting.
there is a [plugin](https://github.com/benhoIIand/grunt-cache-bust) but there is no pug plugin for it.
writing such a plugin would be a waste of time, since webpack is better maintained and there is even a [pug plugin](https://github.com/webdiscus/pug-plugin) for cache busting , swithing to webpack is a good idea in general.

**Comment by JaviTrek** [comment]
@fcaps switching to webpack would be peak, grunt is just terrible all around.

Do you need help with that? It shouldn't be too hard

**Comment by fcaps** [comment]
@JaviTrek you could review the PR :)

open tasks if you like to do them:
- move scss to webpack
- move to webpack devserver (https://webpack.js.org/guides/production/)
- remove whats left from grunt
- update Dockerfile/-dev
