### ISSUE TITLE
Windows Landscape Flipped - Buttons/Screen Layout is incorrectly flipped

### ISSUE THREAD

**Issue by bnyboy** [FAForever/website#51]
When using your screen resolution flipped within windows (ie for a lying/custom desk - landscape flipped) the game client does not flip correctly, and the click locations no longer align with what is displayed on screen.

This is a very custom scenario, it does not warrant a high priority.

**Comment by Raistlfiren** [comment]
Are you referring to the game client?

**Comment by bnyboy** [comment]
Yeah i was, i updated the comment with 'game client'. Thanks.
