### ISSUE TITLE
Make client download page clearer

### ISSUE THREAD

**Issue by duk3luk3** [FAForever/website#57]
(Because of discussion on slack)

There have been reports (by gorton) of users being confused by the download page.

The top of the download page should be changed to something like this:  http://lerlacher.de/static/fafclientdownload.html

"This client is awesome and does awesome things." is a placeholder text and should be replaced by a *short* descriptive paragraph.

The page needs to be designed so that it is clear that this part is the most important part of the page.

**Comment by Raistlfiren** [comment]
@duk3luk3 If I removed the navigation from the client, then it prevents the "Download" button from causing any problems, right? If it doesn't solve your issue, then can you go into more detail. Thanks.

**Comment by duk3luk3** [comment]
I was confused about what the users were mostly confused about. But navigation and download button are fixed on client side now (you should try it!).

But I really mean that the download page should be designed differently. The text at the top isn't very useful and should be replaced by something like I mocked up above.

**Comment by Raistlfiren** [comment]
Got it thanks!

**Comment by lextoc** [comment]
I'm restyling the whole site, going over this when getting to this page.

**Comment by Rackover** [comment]
There is no longer a client download page.
