### ISSUE TITLE
Calendar doesn't show Tournaments - should automatically sync with challonge

### ISSUE THREAD

**Issue by speed2CZ** [FAForever/website#62]

**Comment by speed2CZ** [comment]
Fixed or denied?

**Comment by Raistlfiren** [comment]
The calendar does pull tournaments, there were just none inserted. Should I reopen it for an automatic way of handling them?

**Comment by speed2CZ** [comment]
That would be nice indeed.

**Comment by Raistlfiren** [comment]
This should be fixed based on commit 0de08dcdd62e6e218c469fa3a545362465844ed4

I am closing the issue. Thanks!
