### ISSUE TITLE
General Styles as git submodule

### ISSUE THREAD

**Issue by IDragonfire** [FAForever/website#70]
Suggestion: After merging this the css part, icons, fonts, e.g. should be moved to a seperated general webapp repo and imported as git submodule. Then other apps, e.g. the clanapp can also import the general webapp repo and have the same style!

https://github.com/FAForever/website/pull/69

**Comment by lextoc** [comment]
This is a great idea if it's possible. Being able to re-use styles on all FAF-related websites (that want to) is a big plus.

I **am** going to focus on re-usable CSS components (think of buttons, navigation, footer) which you can use easily, given that you use the appropriate html.

**Comment by Cheyans** [comment]
Make sure there is plain CSS along side any superset language used as all front end based repositories don't necessarily need a compiler for the superset.

**Comment by IDragonfire** [comment]
@Cheyans Why? Nobody use plain CSS anymore ...

**Comment by Cheyans** [comment]
Because that is not true and also for simple repositories let's say the api, for oauth pages there are only a few basic static pages that are displayed. there is no need to include an entire compiler, plain CSS will suffice. Also, not everyone may want to use the same superset language as you.

**Comment by Raistlfiren** [comment]
I agree that we should have a separate repository for CSS components. I think we should include some task processor to handle all SASS file processing and minification.

**Comment by Brutus5000** [comment]
Closed due to inactivity
