### ISSUE TITLE
Calendar - ToggleButtons ignored when switching month

### ISSUE THREAD

**Issue by Geosearchef** [FAForever/website#74]
When switching months in the calendar, the state of the toggle buttons (developer/tournament) is being ignored. It is only applied on the click event.

**Comment by Raistlfiren** [comment]
@Geosearchef - thanks for the issue. I believe it should be corrected in the latest dev version released at test.faforever.com. Please verify this is working properly.

**Comment by Geosearchef** [comment]
Is working!
