### ISSUE TITLE
Show username if logged in

### ISSUE THREAD

**Issue by Brutus5000** [FAForever/website#79]
You can't see your current username anywhere after login.

Suggestion: Show the username right next to the person-icon of the account dropdown.

**Comment by Raistlfiren** [comment]
@Brutus5000 - Can you please look at test.faforever.com and see if the changes that I made will suffice for what you are looking for?

Thanks!

**Comment by Brutus5000** [comment]
Looks good.

**Comment by Raistlfiren** [comment]
Thanks!
