### ISSUE TITLE
Registration page - username requirements not correct

### ISSUE THREAD

**Issue by Brutus5000** [FAForever/website#80]
On the registration page, the only visible requirement to the username is a minimum of 3 characters.
This is not correct. There are way more requirements:
* number of characters between 3 and 16
* Only letters, digits, minus and underscore is allowed
* first character must be a letter

`USERNAME_REGEX = re.compile("[A-Za-z]{1}[A-Za-z0-9_-]{2,15}$")`

**Comment by Raistlfiren** [comment]
Thanks @Brutus5000 - I will try to push something out soon with an update :)
