### ISSUE TITLE
clan login leads to http://_  and  'Accept Request' is inactive (while Reject Request' is active)

### ISSUE THREAD

**Issue by GrotheFAF** [FAForever/website#84]
tried a login on http://clans.faforever.com/    .. lead me to http://_
(when I choose page back and reIoaded, I was logged in.)
I myClan I couldn't accept a Membership request, 'Accept request' is inactive (while Reject request' is active)

**Comment by GrotheFAF** [comment]
anyone ???

**Comment by Raistlfiren** [comment]
This should be posted under the clans repository... Not the website....

**Comment by Raistlfiren** [comment]
@GrotheFAF I brought this up under the clan-app slack channel back in April when you asked.

**Comment by GrotheFAF** [comment]
ok, moved it there.
