### ISSUE TITLE
Add Calendar-ID and ICAL Address

### ISSUE THREAD

**Issue by micheljung** [FAForever/website#90]
Add the calendar ID and ICAL URL to the calendar page:
* Maintenance & Updates Google Calendar-ID: faforever.com_cpellm2p2sdfr8dfmnmgs1davk@group.calendar.google.com
* Maintenance & Updates ICAL: https://calendar.google.com/calendar/ical/faforever.com_cpellm2p2sdfr8dfmnmgs1davk%40group.calendar.google.com/public/basic.ics

**Comment by IDragonfire** [comment]
The calender is cool 
but to make it more useful ical and export options should be added to the page ...

**Comment by micheljung** [comment]
https://en.wikipedia.org/wiki/Calender
https://en.wikipedia.org/wiki/Calendar
